kind: Deployment
apiVersion: apps/v1
metadata:
  name: kens-deployment
  labels:
    visualize: "true"
    run: nginx
  namespace: development
spec:
  selector:
    matchLabels:
      app: kens-app
  replicas: 8
  template:
    metadata:
      labels:
        app: kens-app
        visualize: "true"
        run: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
      tolerations:
      - key: "cloud"
        operator: "Equal"
        value: "private"
        effect: "NoSchedule"
      - key: "cloud"
        operator: "Equal"
        value: "public"
        effect: "NoSchedule"
