kind: Deployment
apiVersion: apps/v1
metadata:
  name: kens-deployment
  labels:
    visualize: "true"
    run: nginx
spec:
  selector:
    matchLabels:
      app: kens-app
  replicas: 2
  template:
    metadata:
      labels:
        app: kens-app
        visualize: "true"
        run: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14
        ports:
        - containerPort: 80
      tolerations:
      - key: "cloud"
        operator: "Equal"
        value: "private"
        effect: "NoSchedule"