kind: Service
apiVersion: v1
metadata:
  name: kens-service
  labels:
    visualize: "true"
    run: nginx
  namespace: development
spec:
  type: LoadBalancer
  selector:
    app: kens-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
