---

filebeatConfig:
  filebeat.yml: |
    filebeat:
      config:
        modules:
          path: /usr/share/filebeat/modules.d/*.yml
          reload:
            enabled: true
      modules:
      - module: system
        syslog:
          enabled: true
          var.paths: ["/host/log/messages*","/host/log/syslog*"]
        auth:
          enabled: true
          var.paths: ["/host/log/auth.log*","/host/log/secure*"]
      inputs:
      - type: log
        paths:
          - /host/log/kern.log*
    output:
      logstash:
        hosts: '${LOGSTASH_HOSTS:logstash-logstash.elastic-system:5044}'

extraVolumeMounts:
  - name: varlog
    mountPath: /host/log
    readOnly: true

extraVolumes:
  - name: varlog
    hostPath:
      path: /var/log
      type: Directory
