---

filebeatConfig:
  filebeat.yml: |
    filebeat:
      config:
        modules:
          path: /usr/share/filebeat/modules.d/*.yml
          reload:
            enabled: true
      modules:
      - module: apache
      - module: system
        syslog:
          enabled: true
        auth:
          enabled: true
      inputs:
      - type: docker
        containers.ids:
          - '*'
        processors:
          - add_kubernetes_metadata: ~
      - type: log
        paths:
          - /var/log/kern.log*
    output:
      elasticsearch:
        host: '${NODE_NAME}'
        hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'
    setup:
      kibana:
        host: '${KIBANA_HOST:kibana-kibana:5601}'
        protocol: "http"
      dashboards:
        enabled: true
