apiVersion: v1
kind: ConfigMap
metadata:
 labels:
   app: tomcat
   component: filebeat
 name: filebeat-logstash-config
data:
  filebeat.yml: |
    filebeat:
      config:
        modules:
          path: /usr/share/filebeat/modules.d/*.yml
          reload:
            enabled: true
      modules:
      - module: apache
        access:
          enabled: true
          var.paths:
          - "/usr/local/tomcat/logs/localhost_access_log.*.txt"
        error:
          enabled: false
    output:
      logstash:
        hosts: '${LOGSTASH_HOSTS:logstash-logstash.elastic-system:5044}'
