---

filebeatConfig:
  filebeat.yml: |
    filebeat:
      config:
        modules:
          path: /usr/share/filebeat/modules.d/*.yml
          reload:
            enabled: true
      modules:
      - module: system
        syslog:
          enabled: true
        auth:
          enabled: true
      inputs:
      - type: docker
        containers.ids:
        - '*'
        processors:
        - add_kubernetes_metadata: ~
      - type: log
        paths:
          - /var/log/kern.log*
    output:
      logstash:
        hosts: '${LOGSTASH_HOSTS:logstash-logstash.elastic-system:5044}'
